version: '3'
services:
  gerrit1:
    image: nats-gerrit:latest
    environment:
      - INSTANCE_ID=primary
      - REPLICA=false
      - REMOTE=replica-1
      - REMOTE_URL=gerrit2
      - DEBUG_PORT=5005
      - BROKER_HOST=${NATS_USER:?}:${NATS_PASSWORD}@${NATS_URL:?}
      - BROKER_SEND_STREAM_EVENTS=true
      - REPLICATE_ON_STARTUP=false
    ports:
      - "8080:8080"
      - "29418:29418"
      - "5005:5005"
  gerrit2:
    image: nats-gerrit:latest
    environment:
      - INSTANCE_ID=replica-1
      - REPLICA=true
      - REMOTE=primary
      - REMOTE_URL=gerrit1
      - DEBUG_PORT=5006
      - BROKER_HOST=${NATS_USER:?}:${NATS_PASSWORD}@${NATS_URL:?}
      - BROKER_SEND_STREAM_EVENTS=false
      - REPLICATE_ON_STARTUP=true
    ports:
      - "8081:8080"
      - "29419:29418"
      - "5006:5006"
    depends_on:
      - gerrit1
